[2023-09-20 20:57:54,912] INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-20 20:57:54,913] INFO [33mPress CTRL+C to quit[0m - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-20 21:00:48,909] INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-20 21:00:48,910] INFO [33mPress CTRL+C to quit[0m - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-21 01:04:38,165] INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-21 01:04:38,165] INFO [33mPress CTRL+C to quit[0m - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-21 01:04:39,780] WARNING Realizando busca por doutores - call_trace=D:\Workspace\MVP\consultas_medicas\rest_api\use_cases\get_doctors.py L7   
[2023-09-21 01:04:39,784] INFO 127.0.0.1 - - [21/Sep/2023 01:04:39] "[31m[1mPOST /agendamento HTTP/1.1[0m" 422 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-21 01:04:39,787] INFO 127.0.0.1 - - [21/Sep/2023 01:04:39] "GET /agendamentos HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-21 01:04:39,835] INFO 127.0.0.1 - - [21/Sep/2023 01:04:39] "GET /doutores HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-21 01:04:39,842] INFO 127.0.0.1 - - [21/Sep/2023 01:04:39] "GET /consultorios?doctor_crm= HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-21 01:06:15,320] WARNING Realizando busca por doutores - call_trace=D:\Workspace\MVP\consultas_medicas\rest_api\use_cases\get_doctors.py L7   
[2023-09-21 01:06:15,323] INFO 127.0.0.1 - - [21/Sep/2023 01:06:15] "GET /doutores HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-21 01:06:24,641] INFO 127.0.0.1 - - [21/Sep/2023 01:06:24] "GET /consultorios?doctor_crm=3804 HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-21 01:07:37,097] WARNING Realizando busca por doutores - call_trace=D:\Workspace\MVP\consultas_medicas\rest_api\use_cases\get_doctors.py L7   
[2023-09-21 01:07:37,100] INFO 127.0.0.1 - - [21/Sep/2023 01:07:37] "GET /doutores HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-21 01:10:27,953] INFO 127.0.0.1 - - [21/Sep/2023 01:10:27] "GET /consultorios?doctor_crm=3711 HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-21 01:11:47,947] WARNING Realizando busca por doutores - call_trace=D:\Workspace\MVP\consultas_medicas\rest_api\use_cases\get_doctors.py L7   
[2023-09-21 01:11:47,949] INFO 127.0.0.1 - - [21/Sep/2023 01:11:47] "GET /doutores HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-21 01:11:50,003] INFO 127.0.0.1 - - [21/Sep/2023 01:11:50] "GET /consultorios?doctor_crm=3804 HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-21 01:12:14,810] INFO 127.0.0.1 - - [21/Sep/2023 01:12:14] "GET /consultorios?doctor_crm=3804 HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-21 01:13:49,924] INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000 - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-21 01:13:49,925] INFO [33mPress CTRL+C to quit[0m - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-21 01:13:55,280] WARNING Realizando busca por doutores - call_trace=D:\Workspace\MVP\consultas_medicas\rest_api\use_cases\get_doctors.py L7   
[2023-09-21 01:13:55,286] INFO 127.0.0.1 - - [21/Sep/2023 01:13:55] "GET /doutores HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-21 01:13:56,316] INFO 127.0.0.1 - - [21/Sep/2023 01:13:56] "GET /consultorios?doctor_crm=3804 HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-21 01:13:58,247] WARNING Coletando agendamentos - call_trace=D:\Workspace\MVP\consultas_medicas\rest_api\use_cases\get_schedule_by_doctor_and_clinic.py L7   
[2023-09-21 01:13:58,252] INFO 127.0.0.1 - - [21/Sep/2023 01:13:58] "GET /encontrar_agendamentos?doctor_crm=3804&clinic=1 HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-21 01:14:24,115] INFO 127.0.0.1 - - [21/Sep/2023 01:14:24] "[31m[1mPOST /agendamento HTTP/1.1[0m" 422 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-21 01:17:16,137] WARNING Realizando busca por doutores - call_trace=D:\Workspace\MVP\consultas_medicas\rest_api\use_cases\get_doctors.py L7   
[2023-09-21 01:17:16,139] INFO 127.0.0.1 - - [21/Sep/2023 01:17:16] "GET /doutores HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-21 01:17:18,073] INFO 127.0.0.1 - - [21/Sep/2023 01:17:18] "GET /consultorios?doctor_crm=3804 HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-21 01:17:52,867] ERROR Exception on /agendamento [POST] - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\flask\app.py L1741
Traceback (most recent call last):
  File "D:\Workspace\MVP\mvp_1\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Workspace\MVP\mvp_1\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Workspace\MVP\mvp_1\lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\Workspace\MVP\mvp_1\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Workspace\MVP\mvp_1\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\Workspace\MVP\mvp_1\lib\site-packages\flask_openapi3\scaffold.py", line 127, in view_func
    response = func(**func_kwargs)
  File "D:\Workspace\MVP\consultas_medicas\rest_api\app.py", line 49, in post_schedule
    return add_schedule(form,session)
  File "D:\Workspace\MVP\consultas_medicas\rest_api\use_cases\add_schedule.py", line 7, in add_schedule
    schedule = Schedule(
  File "<string>", line 4, in __init__
  File "D:\Workspace\MVP\mvp_1\lib\site-packages\sqlalchemy\orm\state.py", line 481, in _initialize_instance
    with util.safe_reraise():
  File "D:\Workspace\MVP\mvp_1\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "D:\Workspace\MVP\mvp_1\lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
  File "D:\Workspace\MVP\mvp_1\lib\site-packages\sqlalchemy\orm\state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "D:\Workspace\MVP\mvp_1\lib\site-packages\sqlalchemy\orm\decl_base.py", line 1197, in _declarative_constructor
    raise TypeError(
TypeError: 'status' is an invalid keyword argument for Schedule
[2023-09-21 01:17:52,904] INFO 127.0.0.1 - - [21/Sep/2023 01:17:52] "[35m[1mPOST /agendamento HTTP/1.1[0m" 500 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-21 01:19:19,862] WARNING Realizando busca por doutores - call_trace=D:\Workspace\MVP\consultas_medicas\rest_api\use_cases\get_doctors.py L7   
[2023-09-21 01:19:19,865] INFO 127.0.0.1 - - [21/Sep/2023 01:19:19] "GET /doutores HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-21 01:19:23,136] INFO 127.0.0.1 - - [21/Sep/2023 01:19:23] "GET /consultorios?doctor_crm=3845 HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
[2023-09-21 01:19:24,639] WARNING Coletando agendamentos - call_trace=D:\Workspace\MVP\consultas_medicas\rest_api\use_cases\get_schedule_by_doctor_and_clinic.py L7   
[2023-09-21 01:19:24,642] INFO 127.0.0.1 - - [21/Sep/2023 01:19:24] "GET /encontrar_agendamentos?doctor_crm=3845&clinic=1 HTTP/1.1" 200 - - call_trace=D:\Workspace\MVP\mvp_1\lib\site-packages\werkzeug\_internal.py L224 
